# ================================================================
# SonarCloud
# ================================================================

sonar.projectKey=eliasss3990_Cooperativa-Financiera-Py_SpringBoot-PostgreSQL
sonar.organization=eliasss3990

sonar.projectName=Cooperativa Financiera Paraguay - Backend
sonar.projectVersion=0.0.1

# Fuentes y tests
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.source=17

# Cobertura (generada por JaCoCo via mvn verify)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports

# Exclusiones
sonar.exclusions=**/generated/**,**/target/**
