spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: false

logging:
  level:
    root: WARN
    developers: DEBUG
